### ISSUE TITLE
Add button loader animation

### ISSUE THREAD

**Issue by akhileshthite** [buidltools/dscan#1]
After clicking on upload button and selecting the file, add button loader animation till the QR code is generated.

Hint:
You can use `this.classList.toggle('btn-loading')`

code example:
```html
 <input type="file" class="loader" onclick="this.classList.toggle('btn-loading')" />
```
```javascript
const btnLoader = document.querySelector(".loader");
btnLoader.classList.add("btn-loading");
```
*You can add button loader animation or whole page loading gif*

![ATB3o](https://user-images.githubusercontent.com/68826419/154296276-9c0e0158-7ea6-4b0b-bfa2-7776c2ddca11.gif)

![ss1](https://user-images.githubusercontent.com/68826419/143767835-f721c235-8e7c-4f1a-b3ad-8c4363e9dd36.jpeg)

Directory structure:
CSS: `/static/style.css`
Main HTML: `/popup.html`
Main js: `/script.js`

**Comment by nishant-siddh** [comment]
Hey, I want to contribute in this

**Comment by nishant-siddh** [comment]
Can u assign it to me, want to work on this

**Comment by akhileshthite** [comment]
> Can u assign it to me, want to work on this

Sure, go ahead.

**Comment by nishant-siddh** [comment]
Hey, is the qr being genereted after particular time or randomly.

**Comment by nishant-siddh** [comment]
Sry man i am bit confuse bout how to hide the loader when the qr loads, as the qr code is being generates at random time.
So i think i need to learn jquey more to do this.

**Comment by nishant-siddh** [comment]
I accidently unassigned myself

**Comment by nishant-siddh** [comment]
Sry @AkhileshThite I accidently unasssigned myself

**Comment by akhileshthite** [comment]
> Sry @AkhileshThite I accidently unasssigned myself

Reassigned.
