### ISSUE TITLE
[feat]: add small "copied" popup feature after clicking on "copy generated CID" svg button

### ISSUE THREAD

**Issue by akhileshthite** [buidltools/dscan#13]
![Screenshot 2022-03-06 at 5 58 29 PM](https://user-images.githubusercontent.com/68826419/156923320-6636eb87-7078-41cc-8f1a-c5817465b505.png)

Code link: 
https://github.com/buidltools/dscan/blob/b6ff5d621213534f8a705901e328a78071240e40/src/js/qrcode.js#L45

Copy function:
```javascript
  // Copy CID to clipboard when copy button is clicked
  $("#svg-cid")
    .off()
    .on("click", function () {
      navigator.clipboard.writeText(cid);
    });
```

For `file structure` and `contributing guide`, check the main [README.md](https://github.com/buidltools/dscan).

**Comment by atifcppprogrammer** [comment]
Hi @AkhileshThite what are you looking for here specifically, from the title i gather that a small tool tip should appear indicating that the generated CID has been copied ? Yes ?

**Comment by akhileshthite** [comment]
> Hi @AkhileshThite what are you looking for here specifically, from the title i gather that a small tool tip should appear indicating that the generated CID has been copied ? Yes ?

Yes. Something like this. but just "copied" text message.
![Screenshot 2022-03-09 at 8 41 00 PM](https://user-images.githubusercontent.com/68826419/157470096-1b088714-b6a9-4352-8875-b10a0dd2ad9b.png)

**Comment by atifcppprogrammer** [comment]
Thanks @AkhileshThite that clears things up, please assign it to me.

**Comment by atifcppprogrammer** [comment]
Hi @AkhileshThite created a pull request for this issue ! please review.

**Comment by akhileshthite** [comment]
> Hi @AkhileshThite created a pull request for this issue ! please review.

Will review soon.
