### ISSUE TITLE
[bug]: loader spinning on the generated QR code

### ISSUE THREAD

**Issue by akhileshthite** [buidltools/dscan#14]

**Comment by atifcppprogrammer** [comment]
Hi @AkhileshThite, i would like to work on this issue, by the way when are you specifically seeing this issue i think i have reproduced it and it seems to occur, when a QR code has been generated and then any subsequent file uploads causes the loader to appear on top of the previous QR code yes ?
<div align="center">
<img src="https://user-images.githubusercontent.com/54069350/157055046-85cb13e9-169e-4bc1-843b-42771a05c6e6.png" alt="bug.png">
</div>

**Comment by akhileshthite** [comment]
> Hi @AkhileshThite, i would like to work on this issue, by the way when are you specifically seeing this issue i think i have reproduced it and it seems to occur, when a QR code has been generated and then any subsequent file uploads causes the loader to appear on top of the previous QR code yes ?
> 
> ![bug.png](https://user-images.githubusercontent.com/54069350/157055046-85cb13e9-169e-4bc1-843b-42771a05c6e6.png)

@atifcppprogrammer  Exactly!
I was about to explain the issue after v2.0 update (cause file structure changes).
I'll assign this issue immediately after i push the v2.0 update tonight.

**Comment by akhileshthite** [comment]
@atifcppprogrammer assigned the issue. 
Please "fetch upstream" v2.0 update changes if you already started working on it.

**Comment by AkhileshThite** [comment]
> @atifcppprogrammer assigned the issue. Please "fetch upstream" v2.0 update changes if you already started working on it.

Make sure to update the

**Comment by atifcppprogrammer** [comment]
Thanks @AkhileshThite.

**Comment by atifcppprogrammer** [comment]
HI @AkhileshThite I created a pull request for this fix.
