### ISSUE TITLE
[bug]: the long URI doesn't fit in the IPFS gateway URI text field

### ISSUE THREAD

**Issue by akhileshthite** [buidltools/dscan#16]
Long URI:
![Screenshot 2022-03-11 at 11 43 09 AM](https://user-images.githubusercontent.com/68826419/157848060-0f9c99c1-828e-448d-9581-47c25d32940c.png)

Should look like this:
![Screenshot 2022-03-11 at 3 45 52 PM](https://user-images.githubusercontent.com/68826419/157848095-f20d3654-b381-45a7-90c7-4f3a75b5cb62.png)

CSS code:
https://github.com/buidltools/dscan/blob/045fd8ace369ec30dc074e2bab138278b31543a3/src/css/popup.css#L194

For `development setup` and `contributing guide`, check the main [README.md](https://github.com/buidltools/dscan).

**Comment by atifcppprogrammer** [comment]
Hi @AkhileshThite, how would you like to address this ? There are one of two ways here, which would you prefer.
1. Make the URI container div **scrollable**.
2. Make the URI container div expand to fit its content.

**Comment by akhileshthite** [comment]
> Hi @AkhileshThite, how would you like to address this ? There are one of two ways here, which would you prefer.
> 
> 1. Make the URI container div **scrollable**.
> 2. Make the URI container div expand to fit its content.

1. It is scrollable already. 
2. No. By expanding its width, it's not going to fit in the extension's window, it won't look good.

There's something with `display:` prop in css.
