### ISSUE TITLE
[feat]: progress percentage UI

### ISSUE THREAD

**Issue by akhileshthite** [buidltools/dscan#20]
Progress percentage should appear in the middle of the loader to check how much percentage of the content (file/folder) is uploaded over IPFS for better UX.

![Screenshot 2022-03-23 at 5 59 13 PM](https://user-images.githubusercontent.com/68826419/159699899-44d83e3b-03e1-4cb3-bbcc-99679497ebe8.png)

### Files:

`HTML`:
For file: https://github.com/buidltools/dscan/blob/main/src/popup.html
For folder: https://github.com/buidltools/dscan/blob/main/src/folderUpload.html

`CSS`: https://github.com/buidltools/dscan/blob/main/src/css/popup.css

`JS`: https://github.com/buidltools/dscan/blob/main/src/js/qrcode.js

For `development setup` and `contribution guide`, check the main [README.md](https://github.com/buidltools/dscan).

**Comment by Nainish-Rai** [comment]
Hey @akhileshthite I want to contribute.

**Comment by akhileshthite** [comment]
> Hey @akhileshthite I want to contribute.

Assigned. Go ahead.

**Comment by Nainish-Rai** [comment]
@akhileshthite is the css incomplete?

**Comment by akhileshthite** [comment]
> @akhileshthite is the css incomplete?

Incomplete?

**Comment by Nainish-Rai** [comment]
@akhileshthite i thought it was css problem, Can u guide me the problem?

**Comment by akhileshthite** [comment]
> @akhileshthite i thought it was css problem, Can u guide me the problem?

It's a new feature. You have to create a progress percentage UI feature as mentioned in the issue.
There is no problem or fix here.

**Comment by zluipaiva** [comment]
hey, I would like to work on this one

**Comment by akhileshthite** [comment]
> hey, I would like to work on this one

Sure. 
Go ahead :D
