### ISSUE TITLE
Extension loses focus on file/folder upload

### ISSUE THREAD

**Issue by anjannair** [buidltools/dscan#25]
**Describe the Bug**

On file/folder upload the extension closes as soon as the focus is shifted to the file picker. This is due to the design of the browser.

**Steps to Reproduce**

1. Open extension
2. Click Upload

**Expected Behavior**

Extension stays in focus and generates QR

**Actual Behavior**

Extension closes but file picker remains

**Additional Details**

A good solution to this may be to open a new window to upload file/folder. Something like how the ad blocking extensions work when you open their logs.

**Comment by akhileshthite** [comment]
Hey @anjannair,
Thanks for noticing. I'll keep this issue open. 
I can assign this to you if you're interested.

**Comment by anjannair** [comment]
@akhileshthite yes I'll try my best to fix!

**Comment by anjannair** [comment]
@akhileshthite a fix is ready for the same if you could somehow fast forward with #24 I can open another PR fixing this issue

**Comment by anjannair** [comment]
The initial pop up when you click the extension
![image](https://user-images.githubusercontent.com/22571613/186150492-667c1537-2bc0-4bd3-9278-8928f96c86b6.png)

The final window
![image](https://user-images.githubusercontent.com/22571613/186150676-c5f9433b-c5c3-49d7-99d6-7d009cd8b6dd.png)

Tested on both FF and Chrome (not tested on Opera, Brave or other Chromium browsers though)

**Comment by akhileshthite** [comment]
> The initial pop up when you click the extension
> 
> ![image](https://user-images.githubusercontent.com/22571613/186150492-667c1537-2bc0-4bd3-9278-8928f96c86b6.png)
> 
> 
> 
> The final window
> 
> ![image](https://user-images.githubusercontent.com/22571613/186150676-c5f9433b-c5c3-49d7-99d6-7d009cd8b6dd.png)
> 
> 
> 
> Tested on both FF and Chrome (not tested on Opera, Brave or other Chromium browsers though)
> 
> 

Got it.
Will review soon.
