### ISSUE TITLE
contributing.md file is missing

### ISSUE THREAD

**Issue by nileshlad09** [buidltools/dscan#26]
According to hacktoberfest guidelines a contributing.md file should be there for projects which are participating in hacktoberfest.
Please assign this issue to me...

**Comment by akhileshthite** [comment]
> According to hacktoberfest guidelines a contributing.md file should be there for projects which are participating in hacktoberfest. Please assign this issue to me...

https://github.com/buidltools/dscan/blob/main/.github/CONTRIBUTING.md
