### ISSUE TITLE
feat: dark mode

### ISSUE THREAD

**Issue by akhileshthite** [buidltools/dscan#28]
Add dark mode toggle and make sure it caches the option.

![Screenshot 2022-10-07 at 2 18 41 PM](https://user-images.githubusercontent.com/68826419/194513639-fc3f85ec-d8ba-4d06-9236-396ba93a8c8f.png)

### Files:

`HTML`:
For file: https://github.com/buidltools/dscan/blob/main/src/popup.html
For folder: https://github.com/buidltools/dscan/blob/main/src/folderUpload.html

`CSS`: https://github.com/buidltools/dscan/blob/main/src/css/popup.css

`JS`: https://github.com/buidltools/dscan/blob/main/src/js/qrcode.js

For `development setup` and `contribution guide`, check the main [README.md](https://github.com/buidltools/dscan).

**Comment by FixxooXD** [comment]
@akhileshthite hey i want to work on this issue i had created a api token but where do i create the .env file what is the root dir file? can you help me out .

**Comment by FixxooXD** [comment]
@akhileshthite  hey i got the buidl folder and added in the extension tab how can i run the project ?

**Comment by g1mishra** [comment]
Hi @FixxooXD

Here is how I am running and testing changes in development.

Command to run: npm run dev

Steps to follow:
1) Click on the extension to open 
2) Righ-click inside the extension popup and click inspect.
3) After making any changes. Go to inspect window and press CTRL + R ( refresh )

**Comment by FixxooXD** [comment]
@g1mishra  thanks it really helps...

**Comment by FixxooXD** [comment]
Hey @akhileshthite I added the Dark-mode toggle switch have a look 👆

**Comment by akhileshthite** [comment]
> Hey @akhileshthite I added the Dark-mode toggle switch have a look 👆

#32 closed.
Reason: [comment](https://github.com/buidltools/dscan/pull/32#issuecomment-1274468941)
