### ISSUE TITLE
feat: colour customisation for QR codes

### ISSUE THREAD

**Issue by akhileshthite** [buidltools/dscan#29]
A colour bar or an input box appears with QR code for customisations.

![Screenshot 2022-10-07 at 2 30 11 PM](https://user-images.githubusercontent.com/68826419/194516511-c82a9f90-1f56-4875-92d8-f792c0319449.png)

### Files:

Colour input:
https://github.com/buidltools/dscan/blob/adaa07878bfef9216f43e0656736e4570af68593/src/js/qrcode.js#L12

`HTML`:
For file: https://github.com/buidltools/dscan/blob/main/src/popup.html
For folder: https://github.com/buidltools/dscan/blob/main/src/folderUpload.html

`CSS`: https://github.com/buidltools/dscan/blob/main/src/css/popup.css

`JS`: https://github.com/buidltools/dscan/blob/main/src/js/qrcode.js

For `development setup` and `contribution guide`, check the main [README.md](https://github.com/buidltools/dscan).

**Comment by g1mishra** [comment]
Hii @akhileshthite 
I would love to work on this.

Please align with me.

**Comment by akhileshthite** [comment]
> Hii @akhileshthite I would love to work on this.
> 
> Please align with me.

Sure :D
Go ahead.

**Comment by g1mishra** [comment]
![16652232896455485673617503312779](https://user-images.githubusercontent.com/48170144/194701997-84eabb30-b8af-4249-8d7e-b4671dbb7b03.jpg)

It was done. 
PR was raised, please check and merge.

Thanks

**Comment by akhileshthite** [comment]
> ![16652232896455485673617503312779](https://user-images.githubusercontent.com/48170144/194701997-84eabb30-b8af-4249-8d7e-b4671dbb7b03.jpg)
> 
> It was done. PR was raised, please check and merge.
> 
> Thanks

Just tested,
It looks amazing! 🔥
Can you do same thing for white colour? 
There would be two bars side-by-side (white one on left and black one on right).
![Screenshot 2022-10-08 at 5 37 14 PM](https://user-images.githubusercontent.com/68826419/194706831-ee4f9dab-4fce-4824-b7d3-2acd37626c3b.png)

**Comment by g1mishra** [comment]
Okay @akhileshthite

**Comment by g1mishra** [comment]
@akhileshthite, I have added a color picker for white color but having an issue with color contrast, and the google scanner is not able to scan properly.

What's your thought on this?

**Comment by akhileshthite** [comment]
> @akhileshthite, I have added a color picker for white color but having an issue with color contrast, and the google scanner is not able to scan properly.
> 
> 
> 
> What's your thought on this?
> 
> 

Okay, I think it's because of the colour combination right?

Push it on different branch let me test.

**Comment by g1mishra** [comment]
Yes @akhileshthite 

Okay, I will push.

After searching on google for a few minutes, I found that the contrast should be 4:1 for the QR code.

**Comment by akhileshthite** [comment]
> Yes @akhileshthite
> 
> Okay, I will push.
> 
> After searching on google for a few minutes, I found that the contrast should be 4:1 for the QR code.

Okay

**Comment by g1mishra** [comment]
@akhileshthite 
I was not able to create a branch in this repo.
So I created it in my forked repo.

Here is the branch: https://github.com/g1mishra/dscan/tree/_feature/qr_colorpicker

**Comment by akhileshthite** [comment]
> @akhileshthite, I have added a color picker for white color but having an issue with color contrast, and the google scanner is not able to scan properly.
> 
> What's your thought on this?

Just tested. It works.
You mean with dark colour backgrounds your scanner is having difficulty?

If you're getting `"504 Gateway Time-out"` error or dealing with long loading time after scanning, then no worries. It's just the `dweb.link` gateway issue.

**Comment by g1mishra** [comment]
Yes @akhileshthite if you choose both colour almost similar. Scanner having difficulty. 

So, should I add latest changes as well in the current PR?

**Comment by akhileshthite** [comment]
> Yes @akhileshthite if you choose both colour almost similar. Scanner having difficulty.
> 
> So, should I add latest changes as well in the current PR?

Yes. 
Do the following changes:

* Like I've mentioned earlier, keep the white bar on left and black one on the right.

![Untitled 001](https://user-images.githubusercontent.com/68826419/194712599-888da42a-251f-4f02-ace7-dfa43fd4ac36.png)

* Run [prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) in the files that you've made changes, the commit message would look something like `style: fix code format using prettier`
* Merge that branch with your main branch, you can do this by sending a PR to your main.

**Comment by g1mishra** [comment]
@akhileshthite Done :)
