### ISSUE TITLE
Error on upload cancel

### ISSUE THREAD

**Issue by zluipaiva** [buidltools/dscan#33]
Define You:

- [x] Contributor

**Describe the Bug**

An error is thrown when you successfully upload a file and then cancel a second file upload. The same happens when uploading folders

**Steps to Reproduce**

While on file upload screen:

1. Click on "Upload" button
2. Select a file and confirm upload
3. Click on "Upload" again
4. Cancel the file upload

**Expected Behavior**

When the second upload is cancelled, the application should not change its state and should continue displaying the previous qr code

**Actual Behavior**

When the upload is cancelled, the app appears to be uploading another file, but the loading stays on 0% and an error is throw in the console.

**Screenshots**

Error message:
![image](https://user-images.githubusercontent.com/23319971/197223941-d5b0564d-4f9c-4ef0-a804-b8c2e1e22383.png)

**Comment by zluipaiva** [comment]
If possible, I would like to work on it!

**Comment by akhileshthite** [comment]
> If possible, I would like to work on it!

Yep, go ahead.
