### ISSUE TITLE
MISSING Code of Conduct and Contribution.md file

### ISSUE THREAD

**Issue by anjaligoswami** [buidltools/dscan#35]
The repository didn't have contribution.md file and code of conduct in it .
I would like to add the files for the same

It would be great if you could assign this issue to me!

**Comment by akhileshthite** [comment]
> The repository didn't have contribution.md file and code of conduct in it . I would like to add the files for the same
> 
> It would be great if you could assign this issue to me!

https://github.com/buidltools/dscan/blob/main/.github/CONTRIBUTING.md
https://github.com/buidltools/dscan/blob/main/.github/CODE_OF_CONDUCT.md
