### ISSUE TITLE
feat: add options to customize qr code styles and logos to qr code

### ISSUE THREAD

**Issue by akhileshthite** [buidltools/dscan#37]

**Comment by weberankit** [comment]
@akhileshthite I would like to contribute to this issue I know Reactjs, JS, CSS, and HTML.
and could you please explain more about what design patterns you want?
plz assigned it to me

**Comment by akhileshthite** [comment]
> @akhileshthite I would like to contribute to this issue I know Reactjs, JS, CSS, and HTML. and could you please explain more about what design patterns you want? plz assigned it to me

Hey @weberankit,
Assigned!
You can start the work.

To implement the `logoPicker` and `stylePicker` features, refer to how the colorPicker is utilized.
