### ISSUE TITLE
Add code of conduct

### ISSUE THREAD

**Issue by akhileshthite** [buidltools/dscan#4]

**Comment by avneesh0612** [comment]
Hey, can I take this one?

**Comment by akhileshthite** [comment]
> Hey, can I take this one?

Sure :)

**Comment by avneesh0612** [comment]
What email should I use?

**Comment by avneesh0612** [comment]
akhileshthite@hotmail.com?

**Comment by akhileshthite** [comment]
> [akhileshthite@hotmail.com](mailto:akhileshthite@hotmail.com)?

Go ahead 👍
