### ISSUE TITLE
refactor: split qrcode script in several files for maintainability

### ISSUE THREAD

**Issue by akhileshthite** [buidltools/dscan#40]
Please break down the `qrcode.js` file into several files for better maintainability.

These files should be:
- ./src/scripts/`web3Storage.js`
- ./src/scripts/`qrHandler.js`
- ./src/scripts/`utils.js`

The file `qrcode.js` is already organized into these sections. However, please ensure you import and export all necessary functions and variables.

> ⚠️ Important: To avoid listeners being called multiple times, ensure they are set only once. You can wrap the listeners in a function and ensure that this function is called just once (or adopt any other solution you prefer).

Source:
[./src/scripts/qrcode.js](https://github.com/p2plabsxyz/dscan/blob/main/src/scripts/qrcode.js)
[./webpack.config.js](https://github.com/p2plabsxyz/dscan/blob/main/webpack.config.js)

> For development setup and contribution guide, check the main [README.md](https://github.com/buidltools/dscan).

**Comment by Pinaka-Pani-18** [comment]
I would like to work on this issue. Could you please assign me this issue ?

**Comment by akhileshthite** [comment]
> I would like to work on this issue. Could you please assign me this issue ?

Sure, go ahead :)

**Comment by Pinaka-Pani-18** [comment]
While installing node modules I getting this following error, do you know how to fix it ?

![Screenshot 2023-10-14 105051](https://github.com/p2plabsxyz/dscan/assets/102857774/981eaede-e1de-4426-98c6-00b090c94d36)

**Comment by akhileshthite** [comment]
> While installing node modules I getting this following error, do you know how to fix it ?
> 
> ![Screenshot 2023-10-14 105051](https://user-images.githubusercontent.com/102857774/275142816-981eaede-e1de-4426-98c6-00b090c94d36.png)

Please make sure you're using the latest stable versions of `npm` and `Node.js`.

**Comment by taran1326** [comment]
Hey can I work on this issue ?  can you assign me ?

**Comment by AdityaNik** [comment]
i want to work on these issue, can you please assign it to me
