### ISSUE TITLE
Add Contributing.md file

### ISSUE THREAD

**Issue by amitkumar-y** [buidltools/dscan#45]
Define You:

- [x ] Contributor

**Is your feature request related to a problem? Please describe.**

For new users who want to contribute to any open-source project, it becomes difficult to start when they are not aware of the basic steps. Having a file that describes the initial steps will be helpful for them.

**Describe the solution you'd like...**

I suggest adding a contributing.md file to the project. You can assign this task to me, and I will create the file

**Comment by akhileshthite** [comment]
https://github.com/p2plabsxyz/dscan/blob/main/.github/CONTRIBUTING.md
