### ISSUE TITLE
bug: size of qrcode is not fixed when data string is different

### ISSUE THREAD

**Issue by akhileshthite** [buidltools/dscan#48]
_Originally posted by @akhileshthite in https://github.com/p2plabsxyz/dscan/pull/46#discussion_r1367903980_

## QR code display issue with long name `files`:
- Files with long names are generating smaller QR codes. Because it's an `URI`; `https://w3s.link/ipfs/<CID>/<file_name>`

![file_qr_code_display_issue](https://github.com/p2plabsxyz/dscan/assets/68826419/eff40049-c2fd-43d2-ac8d-95464e041ad7)

## QR code display issue with `folder`:
- Folders use `URL`; `https://w3s.link/ipfs/<CID>/`, so it's fixed length string.

![folder_qr_code_display_issue](https://github.com/p2plabsxyz/dscan/assets/68826419/b8bd88df-a2bf-47ad-b124-f4a47fb64160)

I tried changing the values here and found that 140 works perfect, but it will mess the file's QR code.
```javascript
export var QR_CODE_DISPLAY = createQRCodeFor(140);
```

## Expected behavior:
The generated QR code should fit in a fixed size `150` regardless of its link length just like previously.

**Comment by Learningcomputers777** [comment]
Can you elaborate more on this issue and provide the files where it is.

**Comment by akhileshthite** [comment]
> Can you elaborate more on this issue and provide the files where it is.

Hey @Learningcomputers777,

Please read this thread https://github.com/p2plabsxyz/dscan/pull/46#discussion_r1367903980_ to learn more about the issue.

Files:
./src/scripts/web3Storage.js
./src/scripts/qrHandler.js
./src/scripts/utils.js
